# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 585c1158705e5db74ca39d28659780ce45749016acb4e708ae316efdbe706b2bdc0be8f2ca7794f2666d17b8d6a825800aa499f93ff9527400c359dff14f00a2

test:
  secret_key_base: f4fd2f577c37cdaa86678f99ddf00f2afd8b9b8ff39a6641e9a5dd770485b8684561aedcb85baf2ab2638a26419720d65815720fb272af2522699f45d4e3162c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
